/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bread: typeof import('./src/components/bread.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ItemPage: typeof import('./src/components/itemPage.vue')['default']
    Itemsmall: typeof import('./src/components/itemsmall.vue')['default']
    ItemTwo: typeof import('./src/components/itemTwo.vue')['default']
    MapPage: typeof import('./src/components/mapPage.vue')['default']
    MapPage0: typeof import('./src/components/mapPage0.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
