/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ItemFour: typeof import('./src/components/itemFour.vue')['default']
    ItemOne: typeof import('./src/components/itemOne.vue')['default']
    ItemPage: typeof import('./src/components/itemPage.vue')['default']
    ItemThree: typeof import('./src/components/itemThree.vue')['default']
    ItemTwo: typeof import('./src/components/itemTwo.vue')['default']
    Map: typeof import('./src/components/map.vue')['default']
    MapPage: typeof import('./src/components/mapPage.vue')['default']
    Mappage0: typeof import('./src/components/mappage0.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
